[project]
name = "conversation-pii-redaction"
version = "0.1.0"
description = "Simple script to redact PII from conversation transcripts"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["pip-system-certs>=5.2", "requests>=2.32.4"]
